# Site settings
title: kingjoshdavid's blog
email: kingjoshdavid@gmail.com
description: "Potentially great stuff, probably junk. I don't really know what I'm doing."
baseurl: "/blog"
url: "http://www.kingjoshdavid.com"
twitter_username: atreys
github_username:  jking-roar

# Build settings
markdown: kramdown
permalink: pretty
